# Generated by Django 5.2.6 on 2025-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('question', 'client_fingerprint')},
        ),
        migrations.AddField(
            model_name='vote',
            name='client_fingerprint',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='ip_address',
        ),
    ]
